import { INDUSTRIES } from "../engine/knowledge/industries";
import { generateIdeas } from "../engine/ideas";
import type { Industry } from "../engine/types";
import { pickUniform, uniformIndex } from "../random";
import type { BusinessIdea, FounderProfile } from "../types";
import { eligibleBusinesses, isEligible, sameShape } from "./eligible";

/**
 * Dealing, kept strictly apart from animating.
 *
 * THE ONE RULE THIS MODULE EXISTS TO ENFORCE
 *
 * **The card is chosen before anything moves.** Nothing about a shuffle, a
 * flip, a position, a duration or a frame rate can reach the result, because
 * by the time the first frame is drawn the answer already exists. That is the
 * property the brief is really asking for when it says the animation must
 * never determine the outcome — and the only way to be sure of it is for the
 * selection to live in a pure module the components merely display.
 *
 * Everything here is pure and synchronous. No React, no timers, no DOM.
 */

export interface IndustryCard {
  kind: "industry";
  id: string;
  title: string;
  industry: Industry;
}

export interface BusinessCard {
  kind: "business";
  id: string;
  title: string;
  idea: BusinessIdea;
}

/**
 * The industry deck: every industry, exactly once.
 *
 * Deliberately *not* shuffled and not sampled. Under Plinko the board could
 * only show ten of eighteen, so which ten appeared was itself a decision the
 * app was making on the founder's behalf. A deck has no such limit — every
 * industry is on the table, the draw is uniform over all of them, and the
 * order they sit in is presentational because the draw does not read it.
 */
export function industryDeck(): IndustryCard[] {
  return INDUSTRIES.map((industry) => ({
    kind: "industry",
    id: industry.id,
    title: industry.label,
    industry,
  }));
}

/** One industry, uniformly. */
export function dealIndustry(): IndustryCard {
  return pickUniform(industryDeck());
}

/**
 * The businesses inside one industry.
 *
 * Generated by the same engine the rest of the app uses, then passed through
 * the same gate as everything else — a card that would be refused from the
 * cross-industry set must not become dealable just because the founder picked
 * its industry first.
 */
export function businessDeck(industryId: string, profile: FounderProfile, seed = 1): BusinessCard[] {
  const ideas = generateIdeas(profile, { industryId, count: 10, seed });
  const kept: BusinessIdea[] = [];

  for (const idea of ideas) {
    if (!isEligible(idea).ok) continue;
    if (kept.some((k) => sameShape(k, idea))) continue;
    kept.push(idea);
  }

  return kept.map((idea) => ({ kind: "business", id: idea.id, title: idea.name, idea }));
}

/** One business from inside a chosen industry, uniformly. */
export function dealBusiness(industryId: string, profile: FounderProfile, seed = 1): BusinessCard | null {
  const deck = businessDeck(industryId, profile, seed);
  return deck.length ? deck[uniformIndex(deck.length)] : null;
}

/**
 * One business from the whole catalogue, uniformly.
 *
 * THIS IS THE MODE WHERE THE FOUNDER PROFILE MUST NOT REACH THE SELECTION.
 *
 * The profile is still passed in, and it still shapes what a candidate *says* —
 * affordability and hours are scored against a real person, and stripping that
 * out would produce a business described for nobody. What it does not do is
 * change which card is drawn: `uniformIndex` takes no profile and there is no
 * ranking step between building the set and picking from it.
 *
 * Keeping those two apart is the whole of the distinction the brief draws
 * between this and "best match for me", which is the existing scored path and
 * is labelled as personalised where it appears.
 */
export function surpriseDeck(profile: FounderProfile, seed = 1): BusinessCard {
  const { businesses } = eligibleBusinesses(profile, seed);
  if (!businesses.length) {
    throw new Error("No eligible businesses — the catalogue or the gate is broken");
  }
  const idea = businesses[uniformIndex(businesses.length)];
  return { kind: "business", id: idea.id, title: idea.name, idea };
}

/**
 * How many things the draw is over, for the page to state.
 *
 * A tool that says "every option has the same chance" without saying how many
 * options there are has told the reader almost nothing. This is what lets the
 * screen say "one of 155" instead.
 */
export function eligibleCount(profile: FounderProfile, seed = 1): number {
  return eligibleBusinesses(profile, seed).businesses.length;
}
