import type { BusinessModel } from "../types";

/**
 * Business model knowledge base.
 *
 * Each model carries its real economics — what it costs to start, how long
 * before money arrives, what capabilities it demands, how it prices, and what
 * usually goes wrong. Ideas are assembled from these, so the constraints in a
 * founder's profile filter the option set before anything is scored.
 *
 * Cost and timing figures are informed estimates for a beginner starting with
 * the equipment they already own. They are shown as estimates everywhere.
 */

const M = (m: BusinessModel) => m;

export const BUSINESS_MODELS: BusinessModel[] = [
  M({
    id: "done-for-you",
    label: "Done-for-you service",
    kind: "service",
    mechanism: "you do the work yourself for one client at a time, and they pay per job",
    startupCost: [0, 60],
    timeToLaunchDays: 5,
    timeToRevenueDays: 10,
    difficulty: 35, scalability: 30, defensibility: 35, margin: 88, predictability: 45,
    minHoursPerWeek: 4,
    needs: [],
    helps: ["sales", "organising"],
    requiresClientCalls: true,
    pricing: { unit: "per project", low: 150, high: 900, recurring: false },
    revenueModel: "One-off project fees, invoiced on delivery",
    delivery: { hoursPerUnit: 6, maxUnits: 8, unitNoun: "project" },
    deliverables: ["An agreed scope with a clear finish line", "The finished work", "A short handover explaining what was done"],
    firstSteps: [
      "Write down exactly what you will and won't do, and what it costs",
      "List 20 specific people or businesses who have this problem right now",
      "Offer the first three a reduced rate in exchange for a testimonial",
    ],
    risks: ["Income stops the moment you do", "Scope creep destroys the hourly rate", "One difficult client can absorb a whole month"],
    channels: ["direct-outreach", "referrals", "local-groups", "linkedin"],
    monetization: ["Project fees", "Retainers once repeat demand appears", "Rush fees for urgent work"],
    mode: "online",
    online: true,
    nameTemplates: ["{topic} for {segment}", "{segment} {topic} service", "The {topic} desk"],
  }),

  M({
    id: "productized-service",
    label: "Productised service",
    kind: "productized-service",
    mechanism: "you sell one tightly-defined package at a fixed price, delivered the same way every time",
    startupCost: [0, 80],
    timeToLaunchDays: 7,
    timeToRevenueDays: 14,
    difficulty: 45, scalability: 55, defensibility: 45, margin: 85, predictability: 60,
    minHoursPerWeek: 5,
    needs: [],
    helps: ["organising", "sales"],
    pricing: { unit: "per package", low: 120, high: 750, recurring: false },
    revenueModel: "Fixed-price packages, often sold as a repeatable monthly slot",
    delivery: { hoursPerUnit: 4, maxUnits: 12, unitNoun: "package" },
    deliverables: ["One clearly-named package", "A fixed turnaround time", "The same checklist every time, so quality doesn't wobble"],
    firstSteps: [
      "Pick the single most requested job and define it as one fixed-price package",
      "Write the checklist you'll follow every time, so delivery is repeatable",
      "Put the price in public — the whole advantage is that nobody has to ask",
    ],
    risks: ["Too narrow a package limits the market", "Fixed price punishes you on awkward jobs", "Copying is easy once it works"],
    channels: ["direct-outreach", "seo", "referrals", "short-video", "linkedin"],
    monetization: ["Fixed-price packages", "Monthly subscription version", "Add-on upgrades"],
    mode: "online",
    online: true,
    nameTemplates: ["{topic} in {n} days", "The {segment} {topic} package", "{topic}, done properly"],
  }),

  M({
    id: "local-service",
    label: "Local service",
    kind: "local-service",
    mechanism: "you travel to customers in your area and do the work in person",
    startupCost: [20, 350],
    timeToLaunchDays: 4,
    timeToRevenueDays: 7,
    difficulty: 30, scalability: 35, defensibility: 45, margin: 78, predictability: 55,
    minHoursPerWeek: 5,
    needs: [],
    helps: ["hands-on", "driving", "sales"],
    requiresLocation: true,
    pricing: { unit: "per visit", low: 45, high: 350, recurring: false },
    revenueModel: "Per-visit charges, with repeat and scheduled work over time",
    delivery: { hoursPerUnit: 2, maxUnits: 40, unitNoun: "job" },
    deliverables: ["The job done to an agreed standard", "Turning up when you said you would", "Before-and-after photos"],
    firstSteps: [
      "Do the job free for two neighbours and photograph the results properly",
      "Post those photos in every local group you belong to, with your price",
      "Knock on the twenty nearest doors where you can see the problem from the street",
    ],
    risks: ["Weather and seasonality", "Travel time eats the margin", "Insurance and licensing obligations"],
    channels: ["local-groups", "door-to-door", "referrals", "google-business", "flyers"],
    monetization: ["Per-visit fees", "Recurring maintenance plans", "Seasonal packages"],
    mode: "local",
    online: false,
    nameTemplates: ["{location} {topic}", "{topic} for {segment}", "The {topic} round"],
  }),

  M({
    id: "consulting",
    label: "Consulting & advisory",
    kind: "consulting",
    mechanism: "people pay for your judgement rather than your hands — you diagnose, they execute",
    startupCost: [0, 40],
    timeToLaunchDays: 5,
    timeToRevenueDays: 12,
    difficulty: 55, scalability: 40, defensibility: 55, margin: 92, predictability: 45,
    minHoursPerWeek: 3,
    needs: [],
    helps: ["research", "teaching", "sales", "data"],
    requiresClientCalls: true,
    pricing: { unit: "per session or audit", low: 90, high: 600, recurring: false },
    revenueModel: "Paid audits and advisory sessions, sometimes retained monthly",
    delivery: { hoursPerUnit: 3, maxUnits: 10, unitNoun: "audit" },
    deliverables: ["A structured review of their situation", "A written set of recommendations, prioritised", "A call to walk them through it"],
    firstSteps: [
      "Turn your knowledge into one repeatable audit with a fixed set of questions",
      "Do three free audits in public and publish what you found (with permission)",
      "Charge from the fourth, at a price you can say out loud without flinching",
    ],
    risks: ["Hard to sell before anyone knows you", "Advice is easy to ignore, which hurts results", "Hourly thinking caps income"],
    channels: ["linkedin", "direct-outreach", "referrals", "newsletter", "long-video"],
    monetization: ["Paid audits", "Monthly advisory retainer", "Group sessions", "A course version later"],
    mode: "online",
    online: true,
    nameTemplates: ["The {topic} audit", "{topic} clinic for {segment}", "{segment} {topic} advisory"],
  }),

  M({
    id: "coaching",
    label: "One-to-one coaching or tuition",
    kind: "education",
    mechanism: "you work with one person repeatedly toward a result they care about",
    startupCost: [0, 40],
    timeToLaunchDays: 4,
    timeToRevenueDays: 9,
    difficulty: 35, scalability: 30, defensibility: 50, margin: 92, predictability: 70,
    minHoursPerWeek: 3,
    needs: ["teaching"],
    helps: ["sales", "fitness", "language"],
    requiresClientCalls: true,
    pricing: { unit: "per hour", low: 25, high: 120, recurring: true },
    revenueModel: "Hourly or block-booked sessions, usually recurring weekly",
    delivery: { hoursPerUnit: 1.5, maxUnits: 20, unitNoun: "session" },
    deliverables: ["Regular sessions", "A plan between sessions so progress continues", "Visible progress tracking"],
    firstSteps: [
      "Define the single outcome you help someone reach, and by roughly when",
      "Offer two free sessions to people who fit exactly, in exchange for honest feedback",
      "Ask both, at the end, what they'd have paid — then price near that",
    ],
    risks: ["Income is capped by your calendar", "Cancellations hit revenue directly", "Emotional labour is real and unpriced"],
    channels: ["local-groups", "referrals", "short-video", "community-posting"],
    monetization: ["Hourly sessions", "Blocks of six or twelve", "Small group version", "A self-serve course later"],
    mode: "hybrid",
    online: true,
    nameTemplates: ["{topic} coaching for {segment}", "{segment} {topic} sessions", "The {topic} programme"],
  }),

  M({
    id: "group-program",
    label: "Group programme",
    kind: "education",
    mechanism: "you teach a cohort the same thing at the same time, so one hour serves many people",
    startupCost: [0, 90],
    timeToLaunchDays: 21,
    timeToRevenueDays: 28,
    difficulty: 60, scalability: 70, defensibility: 55, margin: 88, predictability: 60,
    minHoursPerWeek: 6,
    needs: ["teaching"],
    helps: ["organising", "social", "video"],
    requiresClientCalls: true,
    pricing: { unit: "per seat per cohort", low: 60, high: 400, recurring: false },
    revenueModel: "Cohort fees, run every few weeks",
    delivery: { hoursPerUnit: 10, maxUnits: 3, unitNoun: "cohort" },
    deliverables: ["A fixed-length programme with a clear promise", "Live sessions", "A group where people help each other"],
    firstSteps: [
      "Run the first cohort for six people at a low price, and be honest that it's the first",
      "Record every question asked — that's your real curriculum",
      "Raise the price for cohort two and use the first group's results as proof",
    ],
    risks: ["Needs enough audience to fill a cohort", "Mixed ability levels are hard to teach", "Refund pressure if results vary"],
    channels: ["newsletter", "community-posting", "short-video", "referrals", "linkedin"],
    monetization: ["Cohort fees", "Payment plans", "An ongoing membership after the cohort ends"],
    mode: "online",
    online: true,
    nameTemplates: ["{topic}: {n}-week programme", "The {segment} {topic} cohort", "{topic} bootcamp for {segment}"],
  }),

  M({
    id: "digital-product",
    label: "Digital product",
    kind: "digital-product",
    mechanism: "you make something once — a template, guide, or toolkit — and sell it repeatedly",
    startupCost: [0, 70],
    timeToLaunchDays: 14,
    timeToRevenueDays: 21,
    difficulty: 50, scalability: 88, defensibility: 40, margin: 95, predictability: 40,
    minHoursPerWeek: 4,
    needs: [],
    helps: ["writing", "design", "data", "research"],
    pricing: { unit: "per sale", low: 12, high: 90, recurring: false },
    revenueModel: "One-off sales, ideally with a second product for repeat buyers",
    delivery: { hoursPerUnit: 0.15, maxUnits: 400, unitNoun: "sale" },
    deliverables: ["The product itself, in a format they can use immediately", "Instructions that assume nothing", "Free updates for a stated period"],
    firstSteps: [
      "Find the thing people in your space rebuild from scratch every time — that's the product",
      "Make the smallest useful version and sell it before you polish it",
      "Ask every buyer what nearly stopped them buying, and fix that",
    ],
    risks: ["Easy to copy once visible", "No audience means no sales, however good it is", "Support requests eat the margin at low prices"],
    channels: ["short-video", "seo", "newsletter", "community-posting", "marketplaces"],
    monetization: ["One-off sales", "Bundles", "A premium tier with support", "Licensing to businesses"],
    mode: "online",
    online: true,
    nameTemplates: ["The {segment} {topic} kit", "{topic} templates for {segment}", "The {topic} playbook"],
  }),

  M({
    id: "content-brand",
    label: "Content brand",
    kind: "content",
    mechanism: "you build an audience around a specific subject, then earn from what that audience needs",
    startupCost: [0, 120],
    timeToLaunchDays: 7,
    timeToRevenueDays: 90,
    difficulty: 55, scalability: 92, defensibility: 60, margin: 90, predictability: 25,
    minHoursPerWeek: 6,
    needs: [],
    helps: ["video", "writing", "photo", "social", "audio"],
    pricing: { unit: "per sponsorship or product sale", low: 100, high: 1500, recurring: false },
    revenueModel: "Sponsorship, affiliate income and your own products once the audience exists",
    delivery: { hoursPerUnit: 0, maxUnits: 0, unitNoun: "month",
      audienceDriven: true },
    deliverables: ["Consistent content on one subject", "A place people can subscribe", "Something to sell once there's enough trust"],
    firstSteps: [
      "Choose one subject narrow enough that people can describe your channel in a sentence",
      "Publish twenty pieces before judging anything — the first ten teach you the format",
      "Add an email list on day one; followers are rented, an email list is not",
    ],
    risks: ["Slowest path to a first pound of any model here", "Platform changes can erase reach overnight", "Very easy to quit at month three"],
    channels: ["short-video", "long-video", "seo", "newsletter", "community-posting"],
    monetization: ["Sponsorship", "Affiliate income", "Own digital products", "Memberships", "Platform ad revenue"],
    mode: "online",
    online: true,
    nameTemplates: ["{topic} for {segment}", "The {topic} channel", "{topic} weekly"],
  }),

  M({
    id: "newsletter",
    label: "Niche newsletter",
    kind: "content",
    mechanism: "you write regularly for a specific group, and sell access or sponsorship once they rely on it",
    startupCost: [0, 40],
    timeToLaunchDays: 7,
    timeToRevenueDays: 75,
    difficulty: 45, scalability: 82, defensibility: 65, margin: 92, predictability: 45,
    minHoursPerWeek: 4,
    needs: ["writing"],
    helps: ["research", "data"],
    pricing: { unit: "per subscriber per month or per sponsor slot", low: 5, high: 400, recurring: true },
    revenueModel: "Paid subscriptions, sponsor slots, or both",
    delivery: { hoursPerUnit: 0, maxUnits: 0, unitNoun: "month",
      audienceDriven: true },
    deliverables: ["A predictable issue on a predictable day", "Something genuinely useful in each one", "An archive worth subscribing for"],
    firstSteps: [
      "Pick a group so specific you could name fifty people who'd want it",
      "Write and send the first four issues to people you personally know",
      "Only add paid tiers once people complain when an issue is late",
    ],
    risks: ["Writing weekly is harder than it sounds", "Growth is slow without an existing audience", "Paid conversion is typically low single digits"],
    channels: ["community-posting", "seo", "linkedin", "short-video", "referrals"],
    monetization: ["Paid subscriptions", "Sponsorships", "Job board", "Digital products for the same audience"],
    mode: "online",
    online: true,
    nameTemplates: ["The {topic} brief", "{segment} {topic} weekly", "{topic} notes"],
  }),

  M({
    id: "community",
    label: "Paid community",
    kind: "community",
    mechanism: "you host a group where the members' access to each other is the product",
    startupCost: [0, 60],
    timeToLaunchDays: 14,
    timeToRevenueDays: 30,
    difficulty: 60, scalability: 75, defensibility: 75, margin: 90, predictability: 78,
    minHoursPerWeek: 5,
    needs: [],
    helps: ["social", "teaching", "organising"],
    requiresAudience: true,
    pricing: { unit: "per member per month", low: 8, high: 60, recurring: true },
    revenueModel: "Monthly membership fees",
    delivery: { hoursPerUnit: 0.25, maxUnits: 150, unitNoun: "member" },
    deliverables: ["A space with actual standards", "A reason to show up each week", "Introductions between members"],
    firstSteps: [
      "Gather twenty people free and host one genuinely useful session a week for a month",
      "Watch what they ask each other — that's what they'd pay for",
      "Charge new members from month two, keeping founders free",
    ],
    risks: ["Dead communities are worse than none", "Churn is relentless without a weekly reason to return", "You are the reason it stays alive for a long time"],
    channels: ["community-posting", "newsletter", "short-video", "referrals"],
    monetization: ["Monthly membership", "Annual plans", "Paid events", "Sponsored partner offers"],
    mode: "online",
    online: true,
    nameTemplates: ["The {segment} {topic} room", "{topic} circle", "{segment} collective"],
  }),

  M({
    id: "agency",
    label: "Small agency",
    kind: "agency",
    mechanism: "you win the work and a small bench of freelancers delivers it with you",
    startupCost: [50, 400],
    timeToLaunchDays: 21,
    timeToRevenueDays: 35,
    difficulty: 70, scalability: 70, defensibility: 50, margin: 45, predictability: 70,
    minHoursPerWeek: 12,
    needs: ["sales"],
    helps: ["organising", "design", "video", "social"],
    requiresClientCalls: true,
    pricing: { unit: "per month retained", low: 400, high: 3000, recurring: true },
    revenueModel: "Monthly retainers, delivered partly by subcontractors",
    delivery: { hoursPerUnit: 14, maxUnits: 6, unitNoun: "client" },
    deliverables: ["An agreed monthly scope", "Reporting the client actually reads", "One point of contact who owns the relationship"],
    firstSteps: [
      "Deliver everything yourself for the first two clients so you know the real cost",
      "Write the delivery process down before subcontracting a single task",
      "Only hire against work you already have, never in anticipation",
    ],
    risks: ["Thin margins once you pay others", "Client concentration is dangerous", "You become a manager, whether you wanted to or not"],
    channels: ["direct-outreach", "linkedin", "referrals", "case-studies"],
    monetization: ["Monthly retainers", "Project work", "Performance bonuses", "Referral commissions"],
    mode: "online",
    online: true,
    nameTemplates: ["{topic} studio", "The {segment} {topic} agency", "{topic} partners"],
  }),

  M({
    id: "software",
    label: "Small software tool",
    kind: "software",
    mechanism: "you build a narrow tool that removes one specific piece of repetitive work",
    startupCost: [0, 150],
    timeToLaunchDays: 45,
    timeToRevenueDays: 75,
    difficulty: 85, scalability: 95, defensibility: 70, margin: 88, predictability: 82,
    minHoursPerWeek: 10,
    needs: ["code"],
    helps: ["data", "design", "ai-tools"],
    pricing: { unit: "per user per month", low: 9, high: 79, recurring: true },
    revenueModel: "Monthly subscriptions",
    delivery: { hoursPerUnit: 0.4, maxUnits: 200, unitNoun: "subscriber" },
    deliverables: ["A tool that does one job reliably", "Onboarding that gets someone to value in minutes", "Support that answers quickly"],
    firstSteps: [
      "Solve it manually for five people first, as a service, and charge for that",
      "Automate only the parts you've done by hand enough times to be sure of",
      "Launch to those five before building anything for a sixth",
    ],
    risks: ["Longest time to first revenue here", "Support never stops once you have users", "Easy to build something nobody asked for"],
    channels: ["seo", "community-posting", "direct-outreach", "short-video"],
    monetization: ["Monthly subscriptions", "Annual plans", "One-off lifetime deals early on", "Done-for-you setup fees"],
    mode: "online",
    online: true,
    nameTemplates: ["{topic} for {segment}", "The {topic} tool", "{segment} {topic} tracker"],
  }),

  M({
    id: "ecommerce",
    label: "Niche physical product",
    kind: "ecommerce",
    mechanism: "you sell a physical product to a group mass-market brands ignore",
    startupCost: [120, 900],
    timeToLaunchDays: 35,
    timeToRevenueDays: 45,
    difficulty: 70, scalability: 70, defensibility: 55, margin: 42, predictability: 50,
    minHoursPerWeek: 8,
    needs: [],
    helps: ["crafting", "design", "photo", "sales"],
    requiresInventory: true,
    pricing: { unit: "per order", low: 18, high: 140, recurring: false },
    revenueModel: "Product sales, with repeat orders and bundles over time",
    delivery: { hoursPerUnit: 0.5, maxUnits: 120, unitNoun: "order" },
    deliverables: ["A product that solves something specific", "Photography that answers buyers' real questions", "Delivery that arrives when promised"],
    firstSteps: [
      "Take pre-orders or sell a handmade batch before ordering any stock",
      "Sell twenty units by hand — at a market or in person — before building a shop",
      "Work out your true cost per unit including fees, packaging and returns before pricing",
    ],
    risks: ["Money is tied up in stock that may not sell", "Shipping and returns quietly destroy margins", "Consumer-law and tax obligations apply"],
    channels: ["short-video", "marketplaces", "community-posting", "local-markets"],
    monetization: ["Product sales", "Bundles", "Wholesale to small shops", "Subscription refills"],
    mode: "hybrid",
    online: true,
    nameTemplates: ["{topic} for {segment}", "The {segment} {topic} co", "{topic} supply"],
  }),

  M({
    id: "affiliate-review",
    label: "Review and recommendation site",
    kind: "affiliate",
    mechanism: "you help people choose what to buy, and earn a commission when they do",
    startupCost: [0, 90],
    timeToLaunchDays: 21,
    timeToRevenueDays: 90,
    difficulty: 50, scalability: 85, defensibility: 45, margin: 92, predictability: 35,
    minHoursPerWeek: 5,
    needs: [],
    helps: ["writing", "video", "research", "photo"],
    pricing: { unit: "per commission", low: 3, high: 120, recurring: false },
    revenueModel: "Affiliate commissions, later supplemented by sponsorship or your own products",
    delivery: { hoursPerUnit: 0, maxUnits: 0, unitNoun: "month",
      audienceDriven: true },
    deliverables: ["Honest comparisons that name losers as well as winners", "Recommendations based on real use where possible", "Clear disclosure of every commission"],
    firstSteps: [
      "Pick the ten purchase decisions your audience agonises over most",
      "Write or film the one you know best, and be specific about who each option is wrong for",
      "Disclose affiliate relationships plainly — trust is the whole asset",
    ],
    risks: ["Search and platform changes can wipe out traffic", "Slow to earn anything meaningful", "Undisclosed commissions are illegal in many places"],
    channels: ["seo", "long-video", "short-video", "community-posting"],
    monetization: ["Affiliate commissions", "Sponsorship", "Own digital products", "Consulting for brands"],
    mode: "online",
    online: true,
    nameTemplates: ["{topic} compared", "The {segment} {topic} guide", "Honest {topic} reviews"],
  }),

  M({
    id: "marketplace-connector",
    label: "Matchmaking service",
    kind: "marketplace",
    mechanism: "you connect two groups who struggle to find each other, and charge one side",
    startupCost: [0, 120],
    timeToLaunchDays: 21,
    timeToRevenueDays: 40,
    difficulty: 70, scalability: 78, defensibility: 60, margin: 80, predictability: 50,
    minHoursPerWeek: 7,
    needs: [],
    helps: ["organising", "sales", "social", "research"],
    pricing: { unit: "per successful match", low: 25, high: 400, recurring: false },
    revenueModel: "Placement fees or commission, charged to the side with the money",
    delivery: { hoursPerUnit: 3, maxUnits: 12, unitNoun: "match" },
    deliverables: ["Vetting that actually removes bad options", "Fast matching", "Following up to check it worked"],
    firstSteps: [
      "Do the matching manually by hand — a spreadsheet and a phone is enough to start",
      "Recruit the scarcer side first; the abundant side will always turn up",
      "Charge the side with the budget, not the side with the need",
    ],
    risks: ["Two-sided cold start is genuinely hard", "Both sides will try to cut you out", "Reputation dies with one bad match"],
    channels: ["direct-outreach", "local-groups", "community-posting", "referrals"],
    monetization: ["Placement fees", "Commission", "Subscription for the paying side", "Featured listings"],
    mode: "hybrid",
    online: true,
    nameTemplates: ["{topic} matchmaking", "Find a {topic}", "The {segment} {topic} network"],
  }),

  M({
    id: "events",
    label: "Small events",
    kind: "events",
    mechanism: "you run gatherings people pay to attend, in person or online",
    startupCost: [40, 350],
    timeToLaunchDays: 21,
    timeToRevenueDays: 28,
    difficulty: 55, scalability: 45, defensibility: 60, margin: 60, predictability: 40,
    minHoursPerWeek: 6,
    needs: ["organising"],
    helps: ["social", "teaching", "sales"],
    pricing: { unit: "per ticket", low: 10, high: 120, recurring: false },
    revenueModel: "Ticket sales, plus sponsorship once the event has a track record",
    delivery: { hoursPerUnit: 0.5, maxUnits: 40, unitNoun: "ticket" },
    deliverables: ["A reason to attend that a video call couldn't replace", "An event that runs on time", "Introductions between attendees"],
    firstSteps: [
      "Run the first one small, cheap and free — twelve people in a borrowed room",
      "Sell tickets before booking anything you'd have to pay for",
      "Collect emails at the door; the list is the durable asset, not the event",
    ],
    risks: ["Fixed costs land whether people show or not", "Weather, venues and no-shows", "Public liability insurance is usually needed"],
    channels: ["local-groups", "community-posting", "referrals", "flyers", "newsletter"],
    monetization: ["Tickets", "Sponsorship", "Recordings sold afterwards", "A membership for regulars"],
    mode: "local",
    online: false,
    nameTemplates: ["{location} {topic} meetup", "The {topic} sessions", "{segment} {topic} night"],
  }),

  M({
    id: "content-service",
    label: "Content production service",
    kind: "productized-service",
    mechanism: "you produce content for people who have expertise but no time or skill to publish it",
    startupCost: [0, 80],
    timeToLaunchDays: 7,
    timeToRevenueDays: 14,
    difficulty: 45, scalability: 60, defensibility: 40, margin: 85, predictability: 72,
    minHoursPerWeek: 6,
    needs: [],
    helps: ["video", "writing", "design", "social", "audio"],
    pricing: { unit: "per month", low: 250, high: 1600, recurring: true },
    revenueModel: "Monthly retainers for an agreed volume of content",
    delivery: { hoursPerUnit: 16, maxUnits: 5, unitNoun: "client" },
    deliverables: ["An agreed number of pieces per month", "A consistent look and voice", "A simple approval process that doesn't waste their time"],
    firstSteps: [
      "Make one piece free for an ideal client, unasked, and send it to them",
      "Price monthly from the start — one-off jobs make planning impossible",
      "Cap revisions in writing, or they will expand forever",
    ],
    risks: ["Client taste is subjective and revisions eat margin", "Losing one client is a large percentage of revenue", "Volume commitments become a treadmill"],
    channels: ["direct-outreach", "linkedin", "short-video", "referrals", "case-studies"],
    monetization: ["Monthly retainers", "Per-piece rates for overflow", "Strategy add-ons", "Rush fees"],
    mode: "online",
    online: true,
    nameTemplates: ["{topic} for {segment}", "The {segment} content desk", "{segment} {topic} studio"],
  }),

  M({
    id: "setup-service",
    label: "Setup & migration service",
    kind: "productized-service",
    mechanism: "you set something up properly once for people who'd otherwise get it wrong",
    startupCost: [0, 60],
    timeToLaunchDays: 7,
    timeToRevenueDays: 12,
    difficulty: 50, scalability: 55, defensibility: 45, margin: 90, predictability: 45,
    minHoursPerWeek: 5,
    needs: [],
    helps: ["code", "data", "ai-tools", "organising", "hands-on"],
    pricing: { unit: "per setup", low: 180, high: 1200, recurring: false },
    revenueModel: "One-off setup fees, with optional ongoing maintenance",
    delivery: { hoursPerUnit: 5, maxUnits: 10, unitNoun: "setup" },
    deliverables: ["A working setup, configured properly", "A short recorded walkthrough so they can run it", "A defined support window"],
    firstSteps: [
      "Pick the thing you've set up enough times to do faster than anyone else",
      "Write the setup checklist and time yourself doing it twice",
      "Offer a fixed price with a money-back guarantee — you know how long it takes",
    ],
    risks: ["One-off sales mean starting from zero each month", "Their existing mess can double the work", "Support expectations outlast the fee"],
    channels: ["direct-outreach", "seo", "referrals", "community-posting", "linkedin"],
    monetization: ["Setup fees", "Monthly maintenance", "Training add-on", "Audit before setup"],
    mode: "hybrid",
    online: true,
    nameTemplates: ["{topic} setup for {segment}", "Done-for-you {topic}", "{topic}, configured"],
  }),

  M({
    id: "maintenance-plan",
    label: "Recurring maintenance plan",
    kind: "local-service",
    mechanism: "customers pay monthly for regular upkeep instead of calling in a panic",
    startupCost: [30, 300],
    timeToLaunchDays: 10,
    timeToRevenueDays: 18,
    difficulty: 45, scalability: 50, defensibility: 65, margin: 72, predictability: 88,
    minHoursPerWeek: 6,
    needs: [],
    helps: ["hands-on", "organising", "driving", "code"],
    pricing: { unit: "per month", low: 30, high: 250, recurring: true },
    revenueModel: "Monthly subscriptions for scheduled work",
    delivery: { hoursPerUnit: 1.5, maxUnits: 30, unitNoun: "customer" },
    deliverables: ["A visit or check on a fixed schedule", "A short report each time", "Priority when something goes wrong"],
    firstSteps: [
      "Offer existing one-off customers a monthly plan at a small discount",
      "Set the schedule so a full round is one efficient route or block of time",
      "Send the report even when nothing needed doing — that's what they're paying for",
    ],
    risks: ["Under-pricing recurring work is painful to undo", "Customers forget the value when nothing breaks", "Route density decides whether it's profitable"],
    channels: ["referrals", "local-groups", "door-to-door", "direct-outreach"],
    monetization: ["Monthly plans", "Annual prepay discount", "Callout fees for non-members", "Add-on jobs found during visits"],
    mode: "local",
    online: false,
    nameTemplates: ["{topic} care plan", "{location} {topic} club", "The {topic} round"],
  }),

  M({
    id: "audit-report",
    label: "Paid audit & report",
    kind: "consulting",
    mechanism: "you inspect something and hand over a written verdict people act on",
    startupCost: [0, 60],
    timeToLaunchDays: 6,
    timeToRevenueDays: 10,
    difficulty: 45, scalability: 55, defensibility: 45, margin: 92, predictability: 40,
    minHoursPerWeek: 3,
    needs: [],
    helps: ["research", "data", "writing", "hands-on"],
    pricing: { unit: "per report", low: 60, high: 450, recurring: false },
    revenueModel: "Fixed fee per audit, often leading to the follow-on work",
    delivery: { hoursPerUnit: 2.5, maxUnits: 14, unitNoun: "report" },
    deliverables: ["A structured inspection", "A written report with priorities and rough costs", "A short call to answer questions"],
    firstSteps: [
      "Design a one-page report template so every audit looks the same",
      "Do three free and publish the anonymised findings — they sell the next ten",
      "Price at roughly a tenth of what a mistake in this area typically costs",
    ],
    risks: ["Reports without follow-through don't change anything", "Liability if people act on your assessment", "Each sale is one-off"],
    channels: ["direct-outreach", "seo", "local-groups", "referrals"],
    monetization: ["Per-report fees", "Bundle of audit plus fixes", "Annual re-audit", "White-label for other businesses"],
    mode: "hybrid",
    online: true,
    nameTemplates: ["The {topic} check", "{topic} inspection for {segment}", "{topic} report"],
  }),

  M({
    id: "workshop",
    label: "Workshops & classes",
    kind: "education",
    mechanism: "you teach a group one specific skill in a single session, in person or live online",
    startupCost: [20, 200],
    timeToLaunchDays: 14,
    timeToRevenueDays: 21,
    difficulty: 45, scalability: 55, defensibility: 50, margin: 78, predictability: 45,
    minHoursPerWeek: 4,
    needs: ["teaching"],
    helps: ["organising", "cooking", "crafting", "hands-on", "fitness"],
    pricing: { unit: "per seat", low: 25, high: 150, recurring: false },
    revenueModel: "Per-seat fees, run repeatedly once the format works",
    delivery: { hoursPerUnit: 1.2, maxUnits: 30, unitNoun: "seat" },
    deliverables: ["One skill taught to a usable level in one sitting", "Materials to take away", "Something they made or did during the session"],
    firstSteps: [
      "Teach it free once to six people and time every section",
      "Find a venue that takes a share instead of a fee — cafés, gyms and shops often will",
      "Sell the next session at the end of the current one, while people are still enthusiastic",
    ],
    risks: ["Venue costs land regardless of attendance", "Low-margin without repeat runs", "Insurance and safety obligations for hands-on work"],
    channels: ["local-groups", "flyers", "community-posting", "referrals", "google-business"],
    monetization: ["Seat fees", "Private group bookings", "Recorded version", "Materials kits"],
    mode: "local",
    online: false,
    nameTemplates: ["{topic} workshop", "Learn {topic} in a day", "{segment} {topic} class"],
  }),

  M({
    id: "lead-gen",
    label: "Lead generation for local businesses",
    kind: "agency",
    mechanism: "you generate enquiries for businesses that need customers and pay for results",
    startupCost: [0, 150],
    timeToLaunchDays: 21,
    timeToRevenueDays: 35,
    difficulty: 65, scalability: 70, defensibility: 55, margin: 75, predictability: 60,
    minHoursPerWeek: 8,
    needs: [],
    helps: ["social", "writing", "sales", "code", "design"],
    requiresClientCalls: true,
    pricing: { unit: "per month or per lead", low: 200, high: 1500, recurring: true },
    revenueModel: "Monthly retainer, or a fee per qualified enquiry",
    delivery: { hoursPerUnit: 12, maxUnits: 6, unitNoun: "client" },
    deliverables: ["A steady flow of enquiries", "Proof of where each one came from", "A simple way for them to respond quickly"],
    firstSteps: [
      "Pick one trade and one town — depth beats breadth here",
      "Generate leads first and hand them over free, then ask to be paid for the next batch",
      "Agree in writing what counts as a qualified lead before you start",
    ],
    risks: ["Clients blame you when they fail to follow up", "Attribution arguments are common", "Ad spend can become your risk if you're not careful"],
    channels: ["direct-outreach", "google-business", "local-groups", "case-studies"],
    monetization: ["Monthly retainers", "Per-lead pricing", "Setup fee plus retainer", "Revenue share on closed jobs"],
    mode: "local",
    online: true,
    nameTemplates: ["{location} {topic} leads", "{topic} enquiries for {segment}", "The {topic} pipeline"],
  }),
];

export function modelById(id: string): BusinessModel | undefined {
  return BUSINESS_MODELS.find((m) => m.id === id);
}
