/**
 * What a business is *about*, in one short noun phrase.
 *
 * Keyed on the problem, because the problem is the most descriptive thing about
 * a business — "highlight reels" is what the customer is buying, and it is not
 * derivable from the industry ("sports") or the model ("service").
 *
 * Lifted out of `ideas.ts` so `store.ts` can reach it too: an idea already in
 * someone's vault is re-titled on load, and rebuilding its title needs the same
 * phrase the generator would have used. A second copy of this map would drift,
 * and the symptom would be a stored idea quietly renamed to something the
 * generator never produces.
 */
export const PROBLEM_TOPICS: Record<string, string> = {
  "where-to-go": "spot guides",
  "gear-confusion": "gear advice",
  "skill-gap": "skills coaching",
  "trip-planning": "trip planning",
  "gear-maintenance": "gear care",
  "no-time": "short-session training",
  "no-accountability": "accountability coaching",
  "conflicting-info": "straight-answer coaching",
  "injury-fear": "safe-start training",
  "gym-retention": "member retention",
  "editing-time": "editing",
  "no-ideas": "content planning",
  repurposing: "clip repurposing",
  "on-camera-fear": "on-camera coaching",
  monetisation: "audience monetisation",
  "no-shows": "reliable callouts",
  "small-jobs": "small jobs",
  "seasonal-crunch": "seasonal upkeep",
  trust: "trusted home help",
  "turnover-speed": "tenancy turnarounds",
  "admin-drowning": "admin rescue",
  "quote-slowness": "fast quoting",
  "no-process": "process documentation",
  "cash-visibility": "job profitability",
  "chasing-payment": "invoice chasing",
  "generic-teaching": "one-to-one tuition",
  "intermediate-wall": "intermediate coaching",
  "practice-gap": "practice accountability",
  "exam-technique": "exam technique",
  "training-cost": "practical training",
  "decision-fatigue": "meal planning",
  "restriction-cooking": "restriction-friendly cooking",
  "small-catering": "small-event catering",
  "menu-photos": "food photography",
  "scaling-recipes": "recipe costing",
  "left-alone": "midday visits",
  "conflicting-training": "behaviour coaching",
  "holiday-care": "holiday pet care",
  "grooming-access": "mobile grooming",
  "vet-costs": "preventive pet care",
  "buying-blind": "pre-purchase inspections",
  presentation: "vehicle presentation",
  "garage-trust": "quote checking",
  "project-stalls": "project rescue",
  "fleet-downtime": "fleet upkeep",
  "skill-plateau": "gameplay review",
  "hardware-waste": "build advice",
  "stream-production": "stream production",
  "prep-time": "session prep",
  "finding-players": "group matching",
  "practice-plateau": "practice coaching",
  "unfinished-tracks": "track finishing",
  "bad-audio": "audio cleanup",
  "booking-risk": "performer booking",
  "gear-choices": "studio setup",
  fit: "alterations",
  "no-system": "wardrobe systems",
  "listing-quality": "listing makeovers",
  "occasion-panic": "occasion styling",
  "adaptive-gap": "adaptive clothing",
  "manual-work": "workflow automation",
  "dead-website": "website rescue",
  "tool-sprawl": "systems tidy-up",
  "tech-helplessness": "tech support",
  capacity: "overflow production",
  "no-idea-where": "AI opportunity audits",
  "bad-output": "AI workflow setup",
  "repetitive-writing": "document automation",
  "trust-accuracy": "AI review training",
  "workflow-glue": "tool integration",
  "nothing-specific": "specialist products",
  "listing-conversion": "listing optimisation",
  sourcing: "sourcing help",
  margins: "margin analysis",
  "gift-generic": "personal gifts",
  "first-timer": "event planning",
  "supplier-risk": "supplier vetting",
  "day-of-chaos": "day-of coordination",
  "photo-regret": "event photography",
  "empty-venue": "venue bookings",
  "no-feedback": "performance review",
  "recruiting-maze": "recruiting guidance",
  "club-admin": "club administration",
  "highlight-gap": "highlight reels",
  "injury-prevention": "injury prevention",
  "decision-overload": "household systems",
  stuff: "decluttering",
  "no-village": "parent support",
  "admin-for-others": "carer admin",
  "home-costs": "household bill reviews",
};

/** The phrase for a problem id, with a readable fallback for anything new. */
export function topicForProblem(problemId: string, industryLabel = "specialist"): string {
  return PROBLEM_TOPICS[problemId] ?? `${industryLabel.toLowerCase()} help`;
}
