/**
 * Business Plinko: does chance actually decide, and is the result a business?
 *
 * WHY THIS SUITE EXISTS
 *
 * Two things can quietly go wrong with a discovery game and neither is visible
 * from playing it a few times.
 *
 * The first is **rigging by accident**. A Plinko board is binomial: measured
 * over 60,000 drops, the centre slots take 18.7% each and the outer ones 2.3%.
 * Pin an industry to a slot and the tool recommends the middle one eight times
 * more often than the edge one, silently, wearing the costume of randomness.
 * The fix is to reshuffle the slots before every drop, and this suite is what
 * says the fix works — that the eight-to-one bias lands on positions and the
 * industries come out even.
 *
 * The second is **the board filling with things that are not businesses**. The
 * second board is generated by the same engine the rest of the app uses, so
 * the assertions here are about what reaches the board: specific enough to
 * read, different enough from each other to be a choice, and in the industry
 * that was actually chosen.
 *
 * Run: npm run test:plinko
 */

import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const dir = mkdtempSync(join(tmpdir(), "abb-plinko-"));
const probe = join(dir, "probe.mts");
const cwd = process.cwd();

writeFileSync(
  probe,
  [
    'import { drop, DEFAULT_BOARD, pegs, rng } from "' + cwd + '/src/lib/plinko/physics.ts";',
    'import { industryBoard, businessBoard, boardFor, slotLabel } from "' + cwd + '/src/lib/plinko/discovery.ts";',
    'import { INDUSTRIES } from "' + cwd + '/src/lib/engine/knowledge/industries.ts";',
    'import { emptyProfile } from "' + cwd + '/src/lib/store.ts";',
    "",
    "const results = {};",
    "const p = emptyProfile();",
    "",
    "/* ------------------------------------------------------- the physics --- */",
    "{",
    "  const counts = new Array(DEFAULT_BOARD.slots).fill(0);",
    "  let stuck = 0; let longest = 0;",
    "  const N = 20000;",
    "  for (let s = 0; s < N; s++) {",
    "    const d = drop(s);",
    "    counts[d.slot]++;",
    "    longest = Math.max(longest, d.path.length);",
    "    if (d.path.length >= 1400) stuck++;",
    "  }",
    "  const a = drop(4242); const b = drop(4242);",
    "  results.physics = {",
    "    everySlotReachable: counts.every((c) => c > 0),",
    "    stuck,",
    "    longest,",
    "    deterministic: a.slot === b.slot && a.path.length === b.path.length,",
    "    differentSeedsDiffer: drop(1).slot !== drop(2).slot || drop(1).path.length !== drop(2).path.length,",
    "    /* The bias this suite exists to compensate for, stated as a number. */",
    "    centreOverEdge: ((counts[4] + counts[5]) / 2) / ((counts[0] + counts[counts.length - 1]) / 2),",
    "    hitsSomething: drop(99).hits.length > 0,",
    "    landsInBounds: counts.length === DEFAULT_BOARD.slots,",
    "  };",
    "}",
    "",
    "/* --------------------------------- fairness: the shuffle does its job --- */",
    "{",
    "  const hits = new Map();",
    "  const N = 18000;",
    "  for (let s = 0; s < N; s++) {",
    "    const board = industryBoard(s);",
    "    const d = drop(s * 7919 + 13, boardFor(board.length));",
    "    const id = board[d.slot].industry.id;",
    "    hits.set(id, (hits.get(id) ?? 0) + 1);",
    "  }",
    "  const expected = N / INDUSTRIES.length;",
    "  const ratios = [...hits.values()].map((v) => v / expected);",
    "  results.fairness = {",
    "    everyIndustryReachable: hits.size === INDUSTRIES.length,",
    "    worstOver: Math.max.apply(null, ratios),",
    "    worstUnder: Math.min.apply(null, ratios),",
    "  };",
    "}",
    "",
    "/* --------------------------------------------- the boards themselves --- */",
    "{",
    "  const b1 = industryBoard(11);",
    "  const b2 = industryBoard(12);",
    "  results.industryBoard = {",
    "    full: b1.length === boardFor(DEFAULT_BOARD.slots).slots,",
    "    noDuplicates: new Set(b1.map((s) => s.industry.id)).size === b1.length,",
    "    everyOneLabelled: b1.every((s) => typeof s.label === 'string' && s.label.length > 1),",
    "    differentSeedDifferentBoard: b1.map((s) => s.industry.id).join() !== b2.map((s) => s.industry.id).join(),",
    "    /* Deprioritised, never removed: the pool must not shrink to nothing. */",
    "    stillFullAfterSixSeen: industryBoard(13, INDUSTRIES.slice(0, 6).map((i) => i.id)).length === b1.length,",
    "    avoidsRecent: (() => {",
    "      const recent = INDUSTRIES.slice(0, 6).map((i) => i.id);",
    "      const board = industryBoard(21, recent);",
    "      const repeats = board.filter((s) => recent.includes(s.industry.id)).length;",
    "      return repeats <= 1;",
    "    })(),",
    "  };",
    "}",
    "",
    "/* ------------------------------ every industry yields a usable board --- */",
    "{",
    "  const rows = INDUSTRIES.map((ind) => {",
    "    const board = businessBoard(ind.id, p, 3);",
    "    const names = board.map((s) => s.idea.name);",
    "    const inIndustry = board.filter((s) => s.idea.engine?.industryId === ind.id).length;",
    "    return {",
    "      id: ind.id,",
    "      n: board.length,",
    "      unique: new Set(names).size,",
    "      inIndustry,",
    "      customers: new Set(board.map((s) => s.idea.targetCustomer)).size,",
    "      labelled: board.every((s) => slotLabel(s.label).length > 2),",
    "      specific: names.every((n) => n.split(/\\s+/).length >= 2),",
    "      hasCustomer: board.every((s) => (s.idea.targetCustomer || '').length > 2),",
    "      hasMoney: board.every((s) => (s.idea.revenueModel || '').length > 2),",
    "    };",
    "  });",
    "  results.businessBoards = {",
    "    smallest: Math.min.apply(null, rows.map((r) => r.n)),",
    "    allUnique: rows.every((r) => r.unique === r.n),",
    "    allInChosenIndustry: rows.every((r) => r.inIndustry === r.n),",
    "    everyBoardMultiCustomer: Math.min.apply(null, rows.map((r) => r.customers)),",
    "    allLabelled: rows.every((r) => r.labelled),",
    "    allSpecific: rows.every((r) => r.specific),",
    "    allHaveCustomer: rows.every((r) => r.hasCustomer),",
    "    allHaveMoney: rows.every((r) => r.hasMoney),",
    "    worst: rows.slice().sort((a, b) => a.n - b.n)[0],",
    "  };",
    "}",
    "",
    "/* ------------------------------------ the brief's named test cases B-E --- */",
    "{",
    "  const named = {};",
    "  for (const id of ['automotive', 'food', 'sports', 'fitness', 'home-services', 'pets']) {",
    "    const board = businessBoard(id, p, 5);",
    "    named[id] = {",
    "      n: board.length,",
    "      allInIndustry: board.every((s) => s.idea.engine?.industryId === id),",
    "      sample: board.map((s) => s.idea.name).slice(0, 3),",
    "    };",
    "  }",
    "  results.named = named;",
    "}",
    "",
    "/* -------------------------------------- replay gives something else --- */",
    "{",
    "  const first = businessBoard('automotive', p, 3);",
    "  const again = businessBoard('automotive', p, 3, first.slice(0, 4).map((s) => s.idea.name));",
    "  const firstNames = new Set(first.slice(0, 4).map((s) => s.idea.name));",
    "  results.replay = {",
    "    stillFull: again.length >= 6,",
    "    avoidedTheAvoided: again.filter((s) => firstNames.has(s.idea.name)).length === 0,",
    "    differentSeedDifferentOrder: businessBoard('automotive', p, 9).map((s) => s.idea.name).join() !== first.map((s) => s.idea.name).join(),",
    "  };",
    "}",
    "",
    "/* --------------------------------------------- the label that fits ---- */",
    "results.labels = {",
    "  dropsTheCustomerClause: slotLabel('Highlight Reel Service for Parents of Young Athletes') === 'Highlight Reel Service',",
    "  neverEmpty: slotLabel('X') .length > 0,",
    "  boundedLength: [...INDUSTRIES].every((ind) => businessBoard(ind.id, p, 2).every((s) => slotLabel(s.label).length <= 34)),",
    "};",
    "",
    "console.log(JSON.stringify(results));",
    "",
  ].join("\n"),
  "utf8",
);

const hook = join(cwd, "scripts", "ts-resolve-hook.mjs");
const run = spawnSync(
  process.execPath,
  ["--experimental-strip-types", "--no-warnings", "--experimental-loader", pathToFileURL(hook).href, probe],
  { encoding: "utf8", maxBuffer: 20 * 1024 * 1024 },
);
rmSync(dir, { recursive: true, force: true });

if (run.status !== 0) {
  console.error(run.stderr || run.stdout);
  process.exit(1);
}

const r = JSON.parse(run.stdout.trim().split("\n").pop());

let failures = 0;
const check = (label, ok, detail = "") => {
  if (ok) console.log(`PASS  ${label}${detail ? ` — ${detail}` : ""}`);
  else {
    failures++;
    console.log(`FAIL  ${label}${detail ? ` — ${detail}` : ""}`);
  }
};

console.log("--- the ball is simulated, not chosen ---");
check("every slot is reachable", r.physics.everySlotReachable);
check("no ball ever gets stuck", r.physics.stuck === 0, `${r.physics.stuck} in 20,000, longest path ${r.physics.longest} steps`);
check("and none runs long enough to outstay the animation", r.physics.longest < 600, `${r.physics.longest} steps`);
check("the same seed replays exactly", r.physics.deterministic);
check("different seeds do not", r.physics.differentSeedsDiffer);
check("the ball actually strikes pegs", r.physics.hitsSomething);

console.log("\n--- the bias is real, which is why the slots move ---");
check(
  "the board favours its middle, as every Plinko board does",
  r.physics.centreOverEdge > 3,
  `centre is ${r.physics.centreOverEdge.toFixed(1)}x the edge — this is the thing being compensated for`,
);
check("every industry can still come up", r.fairness.everyIndustryReachable);
check(
  "and no industry is favoured once the slots are shuffled",
  r.fairness.worstOver < 1.15 && r.fairness.worstUnder > 0.85,
  `${r.fairness.worstUnder.toFixed(2)}x to ${r.fairness.worstOver.toFixed(2)}x of even, against an ${r.physics.centreOverEdge.toFixed(1)}x positional bias`,
);

console.log("\n--- the industry board ---");
check("it fills every slot", r.industryBoard.full);
check("with no industry twice", r.industryBoard.noDuplicates);
check("all of them labelled", r.industryBoard.everyOneLabelled);
check("a different drop is a different ten", r.industryBoard.differentSeedDifferentBoard);
check("recent results are pushed back", r.industryBoard.avoidsRecent);
check("but the pool never shrinks — they are deprioritised, not removed", r.industryBoard.stillFullAfterSixSeen);

console.log("\n--- every industry yields a board worth playing ---");
check("no industry returns a thin board", r.businessBoards.smallest >= 6, `smallest is ${r.businessBoards.smallest} (${r.businessBoards.worst.id})`);
check("no board repeats a business", r.businessBoards.allUnique);
check("every option is in the industry that was chosen", r.businessBoards.allInChosenIndustry);
check("and spans more than one kind of customer", r.businessBoards.everyBoardMultiCustomer >= 3, `${r.businessBoards.everyBoardMultiCustomer} at worst`);
check("every option names what it sells", r.businessBoards.allSpecific);
check("every option has a customer", r.businessBoards.allHaveCustomer);
check("and a way of making money", r.businessBoards.allHaveMoney);
check("every slot label fits on the board", r.businessBoards.allLabelled);

console.log("\n--- the brief's named cases ---");
for (const [id, v] of Object.entries(r.named)) {
  check(`${id} returns ${v.n} businesses, all in ${id}`, v.allInIndustry && v.n >= 6, v.sample[0]);
}

console.log("\n--- playing again gives something else ---");
check("a replay is still a full board", r.replay.stillFull);
check("and does not return what was just passed on", r.replay.avoidedTheAvoided);
check("a different drop orders them differently", r.replay.differentSeedDifferentOrder);

console.log("\n--- labels ---");
check("a slot label drops the customer clause", r.labels.dropsTheCustomerClause);
check("and is never empty", r.labels.neverEmpty);
check("and never overruns the board", r.labels.boundedLength);

console.log(failures === 0 ? "\nALL PLINKO TESTS PASSED" : `\n${failures} FAILED`);
process.exit(failures === 0 ? 0 : 1);
